CREATE TABLE empresa (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(100) NOT NULL,
    cnpj       VARCHAR2(18)
);

CREATE TABLE equipamento (
    id_equipamento          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa              NUMBER NOT NULL,
    nome                    VARCHAR2(100) NOT NULL,
    tipo                    VARCHAR2(50),
    status                  VARCHAR2(20) DEFAULT 'LIGADO' NOT NULL,
    limite_consumo_kwh      NUMBER(10,2) NOT NULL,
    limite_ociosidade_min   NUMBER NOT NULL,
    CONSTRAINT fk_equip_empresa
        FOREIGN KEY (id_empresa) REFERENCES empresa(id_empresa),
    CONSTRAINT ck_equip_status
        CHECK (status IN ('LIGADO', 'DESLIGADO', 'ATENCAO'))
);

CREATE TABLE consumo_energia (
    id_consumo          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipamento      NUMBER NOT NULL,
    data_hora           DATE DEFAULT SYSDATE NOT NULL,
    consumo_kwh         NUMBER(10,2) NOT NULL,
    tempo_ocioso_min    NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_consumo_equip
        FOREIGN KEY (id_equipamento) REFERENCES equipamento(id_equipamento)
);

CREATE TABLE alerta (
    id_alerta        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipamento   NUMBER NOT NULL,
    data_hora        DATE DEFAULT SYSDATE NOT NULL,
    tipo_alerta      VARCHAR2(40) NOT NULL,
    mensagem         VARCHAR2(200) NOT NULL,
    status           VARCHAR2(20) DEFAULT 'ABERTO' NOT NULL,
    CONSTRAINT fk_alerta_equip
        FOREIGN KEY (id_equipamento) REFERENCES equipamento(id_equipamento),
    CONSTRAINT ck_alerta_status
        CHECK (status IN ('ABERTO', 'RESOLVIDO'))
);
